# NumPy

#### It is a fundamental package for scientific computing for python. It is a python library that provides a multi dimensional Array object and various derived objects such as Masked Arrays or Metrices and an assortment of routine for fast operations on arrays.

In [2]:
import numpy as np

In [5]:
numpy_array=np.array([1,2,3,4,5])

In [6]:
numpy_array

array([1, 2, 3, 4, 5])

In [7]:
type(numpy_array)

numpy.ndarray

In [9]:
two_daraay=np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5]
])

In [10]:
two_daraay

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [11]:
print(two_daraay)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [12]:
two_daraay.shape

(3, 3)

In [14]:
two_daraay-1

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [15]:
two_daraay[2][1]

np.int64(4)

In [25]:
three_darray=np.array([
    [
        [1,2,3],
        [2,3,4]
    ],
    [
        [1,2,3],
        [8,9,10]
    ]
])

In [26]:
three_darray.shape

(2, 2, 3)

In [27]:
three_darray

array([[[ 1,  2,  3],
        [ 2,  3,  4]],

       [[ 1,  2,  3],
        [ 8,  9, 10]]])

### np.array() ---> Creating the Multidimensional Arrays

##### dtype parameter ---> which can help us out with deciding about the size of the data we are going to store inside our array

In [28]:
np.array([1,2,3,4],dtype=np.int32)

array([1, 2, 3, 4], dtype=int32)

In [34]:
np.array([7,8,9,10,99],dtype=np.int64)

array([ 7,  8,  9, 10, 99])

In [38]:
np.array([7,8,9,10,99,0],dtype=bool)

array([ True,  True,  True,  True,  True, False])

In [40]:
empty_list=[]

for i in range(16):
    empty_list.append(i+1)
print(empty_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]


In [41]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [42]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [52]:
np.linspace(1,4,20)

array([1.        , 1.15789474, 1.31578947, 1.47368421, 1.63157895,
       1.78947368, 1.94736842, 2.10526316, 2.26315789, 2.42105263,
       2.57894737, 2.73684211, 2.89473684, 3.05263158, 3.21052632,
       3.36842105, 3.52631579, 3.68421053, 3.84210526, 4.        ])

In [53]:
arrange_data=np.arange(1,17)

### np.reshape() ----> it helps us out with changing the shape of the array as per our needs

In [58]:
arrange_data.reshape(8,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [59]:
arrange_data.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## ones() --->

In [61]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
np.empty(1)

array([1.])

## Identity() ----> It helps us out with creating the matrix as an Identity Matrix

In [65]:
np.eye(4,4) #identity function

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#random() ---> It helps us creating the random value between 0 to 1 inside the matrix

In [66]:
np.random.rand(2,3)

array([[0.58534298, 0.85728611, 0.54726043],
       [0.30285297, 0.7606755 , 0.63467631]])

In [69]:
np.random.randint(2,8,4)

array([2, 7, 7, 3])

#### linspace() ----> it makes sure that every value with the given range is going to have the similar distance  from each other

In [70]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [72]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

# Attributes

In [73]:
array=np.array([1,2,34])

In [74]:
array.ndim

1

In [81]:
arr=np.array([
    [
    [1,2,3,3],
    [4,5,6,7]
    ],
    [
        [4,5,6,7],
        [65,5,4,3]
    ]
])

In [82]:
print(arr)

[[[ 1  2  3  3]
  [ 4  5  6  7]]

 [[ 4  5  6  7]
  [65  5  4  3]]]


In [83]:
arr.shape

(2, 2, 4)

In [84]:
arr.ndim

3

In [85]:
arr.size

16

In [86]:
arr.dtype

dtype('int64')

In [87]:
arr.itemsize

8

In [88]:
arr.size

16

In [89]:
arr.nbytes

128

In [90]:
arr.T

array([[[ 1,  4],
        [ 4, 65]],

       [[ 2,  5],
        [ 5,  5]],

       [[ 3,  6],
        [ 6,  4]],

       [[ 3,  7],
        [ 7,  3]]])

In [91]:
arr.flat

In [92]:
print(arr.flat)

In [93]:
arr.strides

(64, 32, 8)

In [94]:
arr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [95]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]], dtype=np.int64)

print("shape    :", arr.shape)       # (2, 3)
print("ndim     :", arr.ndim)        # 2
print("size     :", arr.size)        # 6
print("dtype    :", arr.dtype)       # int64
print("itemsize :", arr.itemsize)    # 8
print("nbytes   :", arr.nbytes)      # 48
print("T        :", arr.T.shape)     # (3, 2)
print("flat     :", list(arr.flat))  # [1,2,3,4,5,6]
print("strides  :", arr.strides)     # (24, 8)

shape    : (2, 3)
ndim     : 2
size     : 6
dtype    : int64
itemsize : 8
nbytes   : 48
T        : (3, 2)
flat     : [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6)]
strides  : (24, 8)
