![Task1](images/task1.png)

In [2]:
#importing numpy library

import numpy as np

In [3]:
#creating one d array randomly distributing element using choice()
one_D_array=np.random.choice(range(1,11),size=10,replace=False)

In [4]:
one_D_array.shape #finding the shape of the array

(10,)

In [5]:
one_D_array.dtype #finding the data type of the array

dtype('int64')

In [6]:
two_D_array=np.random.choice(range(1,10),size=(3,3),replace=False)

In [7]:
two_D_array

array([[8, 5, 3],
       [6, 1, 4],
       [2, 9, 7]])

In [8]:
two_D_array.shape

(3, 3)

In [9]:
two_D_array.dtype

dtype('int64')

In [10]:
arr_list=[10,20,30,40,50]
arr=np.array(arr_list)

In [11]:
arr

array([10, 20, 30, 40, 50])

In [12]:
arr.shape

(5,)

In [13]:
arr.dtype

dtype('int64')

![Task2](images/task2.png)

In [14]:
A=np.array([10,20,30,40])
B=np.array([1,2,3,4])

In [15]:
# 01. performing Addition(A+B)
C=A+B
print(C)

[11 22 33 44]


In [16]:
# Extra using np.add to add to array

np.add(A,B)

array([11, 22, 33, 44])

In [17]:
# 02. Performing Subtraction (A-B)

D=A-B
print(D)

[ 9 18 27 36]


In [18]:
# Extra using np.subtract() to subtract the array

np.subtract(A,B)

array([ 9, 18, 27, 36])

In [19]:
# 04. Performing Multiplication

E=A*B
print(E)

[ 10  40  90 160]


In [20]:
# 05. Performing Division

F=A/B
print(F)

[10. 10. 10. 10.]


In [21]:
# 06. Performing Power (A**2)
G=A**2
print(G)

[ 100  400  900 1600]


![Task 3](images/task3.png)

In [22]:
values=np.array([2,4,6,8,10])

# 01. Calculating square root of each element
#sq_root=values**0.5
sq_root=np.sqrt(values)

# 02. Exponential of each element
exp=np.exp(values)

# 03. Natural logarithm of each element
log=np.log(values)

# 04. Sum of all elements
sum_ele=np.sum(values)

# 05. Cumulative sum of elements
cum_sum=np.cumulative_sum(values)


print(f' 01. The Square root of each element in an array {values} is: {sq_root}')
print(f' 02. The Exponential of each element in an array {values} is: {exp}')
print(f' 03. The Natural Logarithmic of each element in an array {values} is: {log}')
print(f' 04. The Sum of all element in an array {values} is: {sum_ele}')
print(f' 05. The cumulative sum of each element in an array {values} is: {cum_sum}')

 01. The Square root of each element in an array [ 2  4  6  8 10] is: [1.41421356 2.         2.44948974 2.82842712 3.16227766]
 02. The Exponential of each element in an array [ 2  4  6  8 10] is: [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
 03. The Natural Logarithmic of each element in an array [ 2  4  6  8 10] is: [0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]
 04. The Sum of all element in an array [ 2  4  6  8 10] is: 30
 05. The cumulative sum of each element in an array [ 2  4  6  8 10] is: [ 2  6 12 20 30]


![task 4](images/task4.png)

In [24]:
# Initilizing the array
data=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

In [25]:
#01. Row-wise sum
np.sum(data,axis=1)

array([ 60, 150, 240])

In [26]:
#02. Column-wise sum
np.sum(data,axis=0)

array([120, 150, 180])

In [30]:
#03. Min value
print(np.min(data))

10


In [31]:
#04. Max value
print(np.max(data))

90


In [32]:
#05. Overall mean
print(np.mean(data))

50.0


![task5](images/task5.png)

In [38]:
#initializing the array
marks=np.array([78,85,90,66,72,88,95,60])

#caculating the tasks
#01-->Mean
mean=np.mean(marks)

#02-->Median
median=np.median(marks)

#03-->Variance
variance=np.var(marks)

#04-->Standard Deviation

s_d=np.sqrt(variance) # we can also do np.std(marks)

#05-->Minimum and maximum
min_max={}
min_max['minimum']=int(np.min(marks))
min_max['maximum']=int(np.max(marks))

#06-->Range(max-min)
ranges=np.max(marks)-np.min(marks)

#Printing the results
print(f'The Mean of marks is {mean}')
print(f'The Median of marks is {median}')
print(f'The Variance of marks is {variance}')
print(f'The Standard Deviation of marks is {s_d:.4f}')
print(f'The Minimum and Maximum of marks is {min_max}')
print(f'The Range of marks is {ranges}')

The Mean of marks is 79.25
The Median of marks is 81.5
The Variance of marks is 134.1875
The Standard Deviation of marks is 11.5839
The Minimum and Maximum of marks is {'minimum': 60, 'maximum': 95}
The Range of marks is 35


![task6](images/task6.png)

In [43]:
#already initialised the marks data in task5 now performing the operations

# 01-->sorting the array
print(np.sort(marks))

# 02-->finding 25 percentile
per1=np.percentile(marks,25)
print(f'25 percentile of the marks is {per1}')

# 03-->finding 50 percentile
per2=np.percentile(marks,50)
print(f'50 percentile of the marks is {per2}')

# 04-->finding 75 percentile
per3=np.percentile(marks,75)
print(f'75 percentile of the marks is {per3}')

# 05-->calculating the no. of students who scored more than average marks
count=0
avg=np.average(marks)
for mark in marks:
    if mark>avg:
        count +=1
print(f'The no. of students who scored more than average marks is: {count}')



# we could have done in one line like this as well
count = np.sum(marks > avg)
print(f'The no. of students who scored more than average marks is: {count}')

[60 66 72 78 85 88 90 95]
25 percentile of the marks is 70.5
50 percentile of the marks is 81.5
75 percentile of the marks is 88.5
The no. of students who scored more than average marks is: 4
The no. of students who scored more than average marks is: 4


![task 7](images/task7.png)

In [66]:
import numpy as np

# initialising the array
sales = np.array([1200, 1500, 900, 2000, 1800, 1700, 1600])
days  = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

# 01 — total weekly sales
weekly_sales = np.sum(sales)
print(f'Total weekly sales    : ₹{weekly_sales}')

# 02 — average daily sales
avg_sales = np.average(sales)
print(f'Average daily sales   : ₹{avg_sales:.2f}')

# 03 — highest and lowest sales day
highest_day = days[np.argmax(sales)]    # day name of highest
lowest_day  = days[np.argmin(sales)]    # day name of lowest

print(f'Highest sales day     : {highest_day} → ₹{np.max(sales)}')
print(f'Lowest sales day      : {lowest_day}  → ₹{np.min(sales)}')

# 04 --> Standard Deviation
sd_sales=np.std(sales)
print(f'Standard Deviation of sales    : ₹{sd_sales:.4f}')

#05-->Identifying days where sales are above avg
days_arr=np.array(days)
mask=sales>np.average(sales)
days_above_avg=days_arr[mask]
sales_above_avg=sales[mask]

print(f'\nDays above average sales (₹{avg_sales:.2f}):')
for day, sale in zip(days_above_avg, sales_above_avg):
    print(f'  {day} → ₹{sale}')

Total weekly sales    : ₹10700
Average daily sales   : ₹1528.57
Highest sales day     : Thursday → ₹2000
Lowest sales day      : Wednesday  → ₹900
Standard Deviation of sales    : ₹345.2299

Days above average sales (₹1528.57):
  Thursday → ₹2000
  Friday → ₹1800
  Saturday → ₹1700
  Sunday → ₹1600
