![Task1](images/task1.png)

In [28]:
#importing numpy library

import numpy as np

In [ ]:
#creating one d array randomly distributing element using choice()
one_D_array=np.random.choice(range(1,11),size=10,replace=False)

In [ ]:
one_D_array.shape #finding the shape of the array

(10,)

In [ ]:
one_D_array.dtype #finding the data type of the array

dtype('int64')

In [19]:
two_D_array=np.random.choice(range(1,10),size=(3,3),replace=False)

In [20]:
two_D_array

array([[2, 9, 4],
       [8, 3, 6],
       [1, 7, 5]])

In [21]:
two_D_array.shape

(3, 3)

In [23]:
two_D_array.dtype

dtype('int64')

In [24]:
arr_list=[10,20,30,40,50]
arr=np.array(arr_list)

In [25]:
arr

array([10, 20, 30, 40, 50])

In [26]:
arr.shape

(5,)

In [27]:
arr.dtype

dtype('int64')

![Task2](images/task2.png)

In [31]:
A=np.array([10,20,30,40])
B=np.array([1,2,3,4])

In [ ]:
# 01. performing Addition(A+B)
C=A+B
print(C)

[11 22 33 44]


In [ ]:
# Extra using np.add to add to array

np.add(A,B)

array([11, 22, 33, 44])

In [34]:
# 02. Performing Subtraction (A-B)

D=A-B
print(D)

[ 9 18 27 36]


In [35]:
# Extra using np.subtract() to subtract the array

np.subtract(A,B)

array([ 9, 18, 27, 36])

In [37]:
# 04. Performing Multiplication

E=A*B
print(E)

[ 10  40  90 160]


In [38]:
# 05. Performing Division

F=A/B
print(F)

[10. 10. 10. 10.]


In [39]:
# 06. Performing Power (A**2)
G=A**2
print(G)

[ 100  400  900 1600]


![Task 3](images/task3.png)

In [42]:
values=np.array([2,4,6,8,10])

# 01. Calculating square root of each element
#sq_root=values**0.5
sq_root=np.sqrt(values)

# 02. Exponential of each element
exp=np.exp(values)

# 03. Natural logarithm of each element
log=np.log(values)

# 04. Sum of all elements
sum_ele=np.sum(values)

# 05. Cumulative sum of elements
cum_sum=np.cumulative_sum(values)


print(f' 01. The Square root of each element in an array {values} is: {sq_root}')
print(f' 02. The Exponential of each element in an array {values} is: {exp}')
print(f' 03. The Natural Logarithmic of each element in an array {values} is: {log}')
print(f' 04. The Sum of all element in an array {values} is: {sum_ele}')
print(f' 05. The cumulative sum of each element in an array {values} is: {cum_sum}')

 01. The Square root of each element in an array [ 2  4  6  8 10] is: [1.41421356 2.         2.44948974 2.82842712 3.16227766]
 02. The Exponential of each element in an array [ 2  4  6  8 10] is: [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
 03. The Natural Logarithmic of each element in an array [ 2  4  6  8 10] is: [0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]
 04. The Sum of all element in an array [ 2  4  6  8 10] is: 30
 05. The cumulative sum of each element in an array [ 2  4  6  8 10] is: [ 2  6 12 20 30]


![task 4](images/task4.png)

In [ ]:
data=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
np.

(3, 3)

![task5](images/task5.png)

![task6](images/task6.png)

![task 7](images/task7.png)